### ISSUE TITLE
Decide on the implementation for URL pre-configuration

### ISSUE THREAD

**Issue by gear54rus** [odin-public/RESTED-APS#19]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**Your envieronment**
Any

**What is the current behavior?**
Currently it is not possible to pre-configure new RESTED APS window by supplying data in the URL.

**What is the expected behavior?**
Look at implementation of https://github.com/RESTEDClient/RESTED/issues/35 and integrate that into an already existing APS data fetching system already created in #16.

**Videos/screenshots of the issue**
N/A

**Comment by eliihen** [comment]
Pushed the WiP implementation here for you to peruse. Note that it is nowhere NEAR done and probably doesn't even compile right now - just figured it is silly for it to be sitting on my laptop.

https://github.com/RESTEDClient/RESTED/compare/next...feature/url-parsing

**Comment by gear54rus** [comment]
Does it work in chrome? I could not find docs on this part of the manifest: https://github.com/RESTEDClient/RESTED/compare/next...feature/url-parsing#diff-51d5ed880643a51e67b69d5e9964bb18R39

**Comment by eliihen** [comment]
`protocol_handlers`? No, that is [Firefox specific](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/protocol_handlers). It adds an entry to the context-menu (right-click) which loads the extension with a URL pattern. But that's not to say you couldn't load it some other way with a compatible URL pattern - that would have the same effect when the extension loads. I assume this is pretty much what you're doing somehow, only that you're using the hash instead of search.

**Comment by gear54rus** [comment]
This will be as it is (via `initFromUrl` in `src/store/options/sagas.js:87`) until further notice.
